Attribute VB_Name = "FunctionHeaders"
Option Explicit

Public Function header_worker(ByVal value As String) As String
  Select Case Trim(value)
   Case "NOMBRE CONTRATO"
    header_worker = "NOMBRE CONTRATO"
   Case "DESTINO"
    header_worker = "DESTINO"
   Case "CIUDAD"
    header_worker = "CIUDAD"
   Case "INGRESO", "INGRESO REGISTRO"
    header_worker = "INGRESO REGISTRO"
   Case "TIPO EXAMEN"
    header_worker = "TIPO EXAMEN"
   Case "FECHA", "FECHA INGRESO"
    header_worker = "FECHA INGRESO"
   Case "PACIENTE"
    header_worker = "PACIENTE"
   Case "NRO IDENFICACION", "NRO IDENTIFICACION"
    header_worker = "NRO IDENFICACION"
   Case "EDADREC", "EDAD"
    header_worker = "EDAD"
   Case "ESTRATO"
    header_worker = "ESTRATO"
   Case "GENERO"
    header_worker = "GENERO"
   Case "NRO HIJOS"
    header_worker = "NRO HIJOS"
   Case "RAZA"
    header_worker = "RAZA"
   Case "ESTADO CIVIL"
    header_worker = "ESTADO CIVIL"
   Case "ESCOLARIDAD"
    header_worker = "ESCOLARIDAD"
   Case "CARGO", "CARGO USUARIO"
    header_worker = "CARGO USUARIO"
   Case "LAB DURACION", "LAB DURACION EN A" & Chr(209) & "OS"
    header_worker = "LAB DURACION EN ANOS"
   Case "FUENTE"
    header_worker = "FUENTE"
   Case "TIPO ACTIVIDAD"
    header_worker = "TIPO ACTIVIDAD"
   Case "idOrdenListaTrabajadores"
    header_worker = "idOrdenListaTrabajadores"
   Case "idOrden"
    header_worker = "idOrden"
   Case Else
    header_worker = "SIN DATO"
  End Select
End Function

Public Function emo_headers(ByVal value As String) As String
  Select Case Trim(value)
   Case "NRO IDENFICACION", "NRO IDENTIFICACION"
    emo_headers = "NRO IDENFICACION"
   Case "TIPO EXAMEN"
    emo_headers = "TIPO EXAMEN"
   Case "RIESGO FISICO / RUIDO", "RIESGO FISICO RUIDO"
    emo_headers = "RIESGO FISICO / RUIDO"
   Case "RIESGO FISICO / ILUMINACION", "RIESGO FISICO ILUMINACION"
    emo_headers = "RIESGO FISICO / ILUMINACION"
   Case "RIESGO FISICO / VIBRACION", "RIESGO FISICO VIBRACION"
    emo_headers = "RIESGO FISICO / VIBRACION"
   Case "RIESGO FISICO / TEMP EXTREMAS", "RIESGO FISICO TEMP EXTREMAS"
    emo_headers = "RIESGO FISICO / TEMP EXTREMAS"
   Case "RIESGO FISICO / PRES ATMOSFERICA", "RIESGO FISICO PRES ATMOSFERICA"
    emo_headers = "RIESGO FISICO / PRES ATMOSFERICA"
   Case "RIESGO FISICO / RAD IONIZANTES", "RIESGO FISICO RAD IONIZANTES"
    emo_headers = "RIESGO FISICO / RAD IONIZANTES"
   Case "RIESGO FISICO / RAD NO IONIZANTES", "RIESGO FISICO RAD NO IONIZANTES"
    emo_headers = "RIESGO FISICO / RAD NO IONIZANTES"
   Case "RIESGO DE OTROS FACTORES FISICOS"
    emo_headers = "RIESGO DE OTROS FACTORES FISICOS"
   Case "RIESGO BIOLOGICO / VIRUS", "RIESGO BIOLOGICO VIRUS"
    emo_headers = "RIESGO BIOLOGICO / VIRUS"
   Case "RIESGO BIOLOGICO / BACTERIAS", "RIESGO BIOLOGICO BACTERIAS"
    emo_headers = "RIESGO BIOLOGICO / BACTERIAS"
   Case "RIESGO BIOLOGICO / HONGOS", "RIESGO BIOLOGICO HONGOS"
    emo_headers = "RIESGO BIOLOGICO / HONGOS"
   Case "RIESGO BIOLOGICO / RICKETSIAS", "RIESGO BIOLOGICO RICKETSIAS"
    emo_headers = "RIESGO BIOLOGICO / RICKETSIAS"
   Case "RIESGO BIOLOGICO / PARASITOS", "RIESGO BIOLOGICO PARASITOS"
    emo_headers = "RIESGO BIOLOGICO / PARASITOS"
   Case "RIESGO BIOLOGICO / FLUIDOS", "RIESGO BIOLOGICO FLUIDOS"
    emo_headers = "RIESGO BIOLOGICO / FLUIDOS"
   Case "RIESGO BIOLOGICO / PICADURAS", "RIESGO BIOLOGICO PICADURAS"
    emo_headers = "RIESGO BIOLOGICO / PICADURAS"
   Case "RIESGO BIOLOGICO / MORDEDURAS", "RIESGO BIOLOGICO MORDEDURAS"
    emo_headers = "RIESGO BIOLOGICO / MORDEDURAS"
   Case "OTROS RIESGOS BIOLOGICOS"
    emo_headers = "OTROS RIESGOS BIOLOGICOS"
   Case "RIESGO QUIMICO / POLVOS", "RIESGO_QCO/POLVOS", "RIESGO QUIMICO POLVOS"
    emo_headers = "RIESGO QUIMICO / POLVOS"
   Case "RIESGO QUIMICO / FIBRAS", "RIESGO QUIMICO FIBRAS"
    emo_headers = "RIESGO QUIMICO / FIBRAS"
   Case "RIESGO QUIMICO / LIQUIDOS", "RIESGO QUIMICO LIQUIDOS"
    emo_headers = "RIESGO QUIMICO / LIQUIDOS"
   Case "RIESGO QUIMICO /GASES", "RIESGO QUIMICO GASES", "RIESGO QUIMICO /HUMOS-GASES"
    emo_headers = "RIESGO QUIMICO /GASES"
   Case "RIESGO QUIMICO / VAPORES", "RIESGO QUIMICO VAPORES"
    emo_headers = "RIESGO QUIMICO / VAPORES"
   Case "RIESGO QUIMICO / HUMOS", "RIESGO_QCO/HUMOS", "RIESGO QUIMICO HUMOS"
    emo_headers = "RIESGO QUIMICO / HUMOS"
   Case "RIESGO QUIMICO /MATERIAL PARTICULADO", "RIESGO QUIMICO MATERIAL PARTICULADO"
    emo_headers = "RIESGO QUIMICO /MATERIAL PARTICULADO"
   Case "OTROS RIESGOS QUIMICOS"
    emo_headers = "OTROS RIESGOS QUIMICOS"
   Case "RIESGO PSICO / GESTION ORGANIZACIONAL", "RIESGO PSICO GESTION ORGANIZACIONAL"
    emo_headers = "RIESGO PSICO / GESTION ORGANIZACIONAL"
   Case "RIESGO PSICO / CARACT DEL GRUPO", "RIESGO PSICO CARACT DEL GRUPO"
    emo_headers = "RIESGO PSICO / CARACT DEL GRUPO"
   Case "RIESGO PSICO / INTERFACES TAREA", "RIESGO PSICO INTERFACES TAREA"
    emo_headers = "RIESGO PSICO / INTERFACES TAREA"
   Case "RIESGO PSICO / CARACT ORGANIZACION", "RIESGO PSICO CARACT ORGANIZACION", "RIESGO PSICO / CARACT ORGANIZACI" & Chr(211) & "N"
    emo_headers = "RIESGO PSICO / CARACT ORGANIZACION"
   Case "RIESGO PSICO / CONDICIONES", "RIESGO PSICO CONDICIONES"
    emo_headers = "RIESGO PSICO / CONDICIONES"
   Case "RIESGO PSICO / JORNADA", "RIESGO PSICO JORNADA"
    emo_headers = "RIESGO PSICO / JORNADA"
   Case "OTROS PSICO LABORAL"
    emo_headers = "OTROS PSICO LABORAL"
   Case "RIESGO_BIOMECANICO_POSTURA"
    emo_headers = "RIESGO_BIOMECANICO_POSTURA"
   Case "RIESGO_BIOMECANICO_ESFUERZO"
    emo_headers = "RIESGO_BIOMECANICO_ESFUERZO"
   Case "RIESGO_BIOMECANICO_MOVREPETITIVO"
    emo_headers = "RIESGO_BIOMECANICO_MOVREPETITIVO"
   Case "RIESGO_BIOMECANICO_MANIPULACION_CARGA"
    emo_headers = "RIESGO_BIOMECANICO_MANIPULACION_CARGA"
   Case "OTROS RIESGOS BIOMECANICOS"
    emo_headers = "OTROS RIESGOS BIOMECANICOS"
   Case "CONDICIONES DE SEGURIDAD / MECANICOS", "CONDICIONES DE SEGURIDAD MECANICOS"
    emo_headers = "CONDICIONES DE SEGURIDAD / MECANICOS"
   Case "CONDICIONES DE SEGURIDAD / ELECTRICOS", "CONDICIONES DE SEGURIDAD ELECTRICOS"
    emo_headers = "CONDICIONES DE SEGURIDAD / ELECTRICOS"
   Case "CONDICIONES DE SEGURIDAD / LOCATIVO", "CONDICIONES DE SEGURIDAD LOCATIVO"
    emo_headers = "CONDICIONES DE SEGURIDAD / LOCATIVO"
   Case "CONDICIONES DE SEGURIDAD / TECNOLOGICO", "CONDICIONES DE SEGURIDAD TECNOLOGICO"
    emo_headers = "CONDICIONES DE SEGURIDAD / TECNOLOGICO"
   Case "CONDICIONES DE SEGURIDAD / ACC DE TRANSITO", "CONDICIONES DE SEGURIDAD ACC DE TRANSITO"
    emo_headers = "CONDICIONES DE SEGURIDAD / ACC DE TRANSITO"
   Case "CONDICIONES DE SEGURIDAD / PUBLICOS", "CONDICIONES DE SEGURIDAD PUBLICOS"
    emo_headers = "CONDICIONES DE SEGURIDAD / PUBLICOS"
   Case "CONDICIONES DE SEGURIDAD / TRABAJO EN ALTURAS", "CONDICIONES DE SEGURIDAD TRABAJO EN ALTURAS"
    emo_headers = "CONDICIONES DE SEGURIDAD / TRABAJO EN ALTURAS"
   Case "CONDICIONES DE SEGURIDAD / ESPACIOS CONFINADOS", "CONDICIONES DE SEGURIDAD ESPACIOS CONFINADOS"
    emo_headers = "CONDICIONES DE SEGURIDAD / ESPACIOS CONFINADOS"
   Case "CONDICIONES DE SEGURIDAD / OTROS DE SEGURIDAD", "CONDICIONES DE SEGURIDAD OTROS DE SEGURIDAD"
    emo_headers = "CONDICIONES DE SEGURIDAD / OTROS DE SEGURIDAD"
   Case "FENOMENOS NATURALES / SISMO", "FENOMENOS NATURALES SISMO"
    emo_headers = "FENOMENOS NATURALES / SISMO"
   Case "FENOMENOS NATURALES / TERREMOTO", "FENOMENOS NATURALES TERREMOTO"
    emo_headers = "FENOMENOS NATURALES / TERREMOTO"
   Case "FENOMENOS NATURALES / VENDAVAL", "FENOMENOS NATURALES VENDAVAL"
    emo_headers = "FENOMENOS NATURALES / VENDAVAL"
   Case "FENOMENOS NATURALES / INUNDACION", "FENOMENOS NATURALES INUNDACION"
    emo_headers = "FENOMENOS NATURALES / INUNDACION"
   Case "FENOMENOS NATURALES / DERRUMBE", "FENOMENOS NATURALES DERRUMBE"
    emo_headers = "FENOMENOS NATURALES / DERRUMBE"
   Case "FENOMENOS NATURALES / PRECIPITACIONES", "FENOMENOS NATURALES PRECIPITACIONES"
    emo_headers = "FENOMENOS NATURALES / PRECIPITACIONES"
   Case "FENOMENOS NATURALES / OTROS NATURALES", "FENOMENOS NATURALES OTROS NATURALES"
    emo_headers = "FENOMENOS NATURALES / OTROS NATURALES"
   Case "FECHA ACCIDENTE"
    emo_headers = "FECHA ACCIDENTE"
   Case "ACCIDENTE_PASO_EN_EMPRESA"
    emo_headers = "ACCIDENTE_PASO_EN_EMPRESA"
   Case "TIPO ACCIDENTE"
    emo_headers = "TIPO ACCIDENTE"
   Case "NATURALEZA LESION"
    emo_headers = "NATURALEZA LESION"
   Case "PARTE AFECTADA"
    emo_headers = "PARTE AFECTADA"
   Case "INCAPACIDAD", "DIAS DE INCAPACIDAD", "DIAS INCAPACIDAD"
    emo_headers = "INCAPACIDAD"
   Case "SECUELAS"
    emo_headers = "SECUELAS"
   Case "NOMBRE ENFERMEDAD"
    emo_headers = "NOMBRE ENFERMEDAD"
   Case "ETAPA"
    emo_headers = "ETAPA"
   Case "OBSERVACIONES DE ENFERMEDAD", "DESCRIPCION"
    emo_headers = "OBSERVACIONES DE ENFERMEDAD"
   Case "ACT_ FISICA"
    emo_headers = "ACT_ FISICA"
   Case "FUMA"
    emo_headers = "FUMA"
   Case "CONSUMO DE ALCOHOL"
    emo_headers = "CONSUMO DE ALCOHOL"
   Case "PESO"
    emo_headers = "PESO"
   Case "TALLA"
    emo_headers = "TALLA"
   Case "TENSION ARTERIAL", "TENSION_ARTERIAL"
    emo_headers = "TENSION ARTERIAL"
   Case "FREC_ CARDIACA"
    emo_headers = "FREC_ CARDIACA"
   Case "FREC_ RESPIRATORIA"
    emo_headers = "FREC_ RESPIRATORIA"
   Case "PERIMETRO ABDOMINAL"
    emo_headers = "PERIMETRO ABDOMINAL"
   Case "LATERALIDAD"
    emo_headers = "LATERALIDAD"
   Case "OBS DIAGS"
    emo_headers = "OBS DIAGS"
   Case "CONCEPTO DE EVALUACION", "CONCEPTO DE EVALUACI" & Chr(211) & "N"
    emo_headers = "CONCEPTO DE EVALUACION"
   Case "OBSERVACIONES DEL CONCEPTO"
    emo_headers = "OBSERVACIONES DEL CONCEPTO"
   Case "REMISION EPS"
    emo_headers = "REMISION EPS"
   Case "CONTROL PERIODICO OCUPACIONAL"
    emo_headers = "CONTROL PERIODICO OCUPACIONAL"
   Case "UTILIZACION EPP ACORDE AL CARGO"
    emo_headers = "UTILIZACION EPP ACORDE AL CARGO"
   Case "REALIZACION DE PRUEBAS COMPLEMENTARIAS"
    emo_headers = "REALIZACION DE PRUEBAS COMPLEMENTARIAS"
   Case "HABITOS NUTRICIONALES"
    emo_headers = "HABITOS NUTRICIONALES"
   Case "EJERCICIO REGULAR 3 VECES POR SEMANA"
    emo_headers = "EJERCICIO REGULAR 3 VECES POR SEMANA"
   Case "DEJAR DE FUMAR"
    emo_headers = "DEJAR DE FUMAR"
   Case "REDUCIR CONSUMO ALCOHOL"
    emo_headers = "REDUCIR CONSUMO ALCOHOL"
   Case "OBSERVACIONES"
    emo_headers = "OBSERVACIONES"
   Case "OSTEOMUSCULAR"
    emo_headers = "OSTEOMUSCULAR"
   Case "VISUAL"
    emo_headers = "VISUAL"
   Case "ALTURAS"
    emo_headers = "ALTURAS"
   Case "BIOLOGICO"
    emo_headers = "BIOLOGICO"
   Case "MANIPULACION DE ALIMENTOS"
    emo_headers = "MANIPULACION DE ALIMENTOS"
   Case "QUIMICO"
    emo_headers = "QUIMICO"
   Case "CUIDADO DE LA VOZ"
    emo_headers = "CUIDADO DE LA VOZ"
   Case "TEMPERATURAS EXTREMAS"
    emo_headers = "TEMPERATURAS EXTREMAS"
   Case "ESPACIOS CONFINADOS"
    emo_headers = "ESPACIOS CONFINADOS"
   Case "PIEL"
    emo_headers = "PIEL"
   Case "RESPIRATORIA"
    emo_headers = "RESPIRATORIA"
   Case "AUDITIVO"
    emo_headers = "AUDITIVO"
   Case "RECOMENDACIONES ESPECIFICAS"
    emo_headers = "RECOMENDACIONES ESPECIFICAS"
   Case "id_emo"
    emo_headers = "ID_EMO"
   Case Else
    emo_headers = "SIN DATO"
  End Select
End Function

Public Function emphasis_headers(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "IDENTIFICACION", "NRO IDENFICACION", "NRO IDENTIFICACION"
    emphasis_headers = "IDENTIFICACION"
   Case "TIPO EXAMEN"
    emphasis_headers = "TIPO EXAMEN"
   Case "ENFASIS_" & x, "ENFASIS " & x,"ENFASIS" & x
    emphasis_headers = "ENFASIS_" & x
   Case "CONCEPTO AL ENFASIS_" & x, "CONCEPTO AL ENFASIS " & x,"CONCEPTO_AL_ENFASIS_" & x
    emphasis_headers = "CONCEPTO AL ENFASIS_" & x
   Case "OBSERVACIONES_AL_ENFASIS_" & x, "OBSERVACIONES AL ENFASIS " & x, "OBSERVACIONES AL ENFASIS_" & x, "OBSERVACIONES_AL_ENFASIS " & x
    emphasis_headers = "OBSERVACIONES_AL_ENFASIS_" & x
    x = x + 1
   Case Else
    emphasis_headers = "SIN DATO"
  End Select
End Function

Public Function diagnostics_header(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "IDENTIFICACION", "NRO IDENFICACION", "NRO IDENTIFICACION"
    diagnostics_header = "IDENTIFICACION"
   Case "TIPO EXAMEN"
    diagnostics_header = "TIPO EXAMEN"
   Case "CODIGO DIAG PPAL"
    diagnostics_header = "CODIGO DIAG PPAL"
   Case "DIAG PPAL"
    diagnostics_header = "DIAG PPAL"
   Case "CODIGO DIAG REL" & x, "CODIGO DIAG REL " & x, "CODIGO DIAG REL" & x, "CODIGO DIAG REL" & x &","
    diagnostics_header = "CODIGO DIAG REL" & x
   Case "DIAG REL " & x, "DIAG REL" & x
    diagnostics_header = "DIAG REL " & x
    x = x + 1
   Case Else
    diagnostics_header = "SIN DATO"
  End Select
End Function

Public Function opto_headers(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "IDENTIFICACION", "NRO IDENFICACION", "NRO IDENTIFICACION"
    opto_headers = "IDENTIFICACION"
   Case "TIPO EXAMEN"
    opto_headers = "TIPO EXAMEN"
   Case "VISIO/ANT_ LABORAL ILUMINACION INADECUADA"
    opto_headers = "VISIO/ANT_ LABORAL ILUMINACION INADECUADA"
   Case "VISIO/ANT_ LABORAL USUARIO COMPUTADOR"
    opto_headers = "VISIO/ANT_ LABORAL USUARIO COMPUTADOR"
   Case "VISIO/ANT_ LABORALVISIO RADIACIONES UV", "VISIO/ANT_ LABORAL VISIO RADIACIONES UV"
    opto_headers = "VISIO/ANT_ LABORALVISIO RADIACIONES UV"
   Case "VISIO/ANT_ LABORAL CAMBIOS TEMPREATURA", "VISIO/ANT_ LABORAL CAMBIOS TEMPERATURA"
    opto_headers = "VISIO/ANT_ LABORAL CAMBIOS TEMPREATURA"
   Case "VISIO/ANT_ LABORAL MALA VENTILACION"
    opto_headers = "VISIO/ANT_ LABORAL MALA VENTILACION"
   Case "VISIO/ANT_ LABORAL GASES TOXICOS"
    opto_headers = "VISIO/ANT_ LABORAL GASES TOXICOS"
   Case "SINTOMAS FOTOFOBIA"
    opto_headers = "SINTOMAS FOTOFOBIA"
   Case "SINTOMAS OJO ROJO"
    opto_headers = "SINTOMAS OJO ROJO"
   Case "SINTOMAS LAGRIMEO"
    opto_headers = "SINTOMAS LAGRIMEO"
   Case "SINTOMAS VISION BORROSA"
    opto_headers = "SINTOMAS VISION BORROSA"
   Case "SINTOMAS ARDOR"
    opto_headers = "SINTOMAS ARDOR"
   Case "SINTOMAS VISION DOBLE"
    opto_headers = "SINTOMAS VISION DOBLE"
   Case "SINTOMAS CANSANCIO"
    opto_headers = "SINTOMAS CANSANCIO"
   Case "SINTOMAS MALA VISION CERCANA"
    opto_headers = "SINTOMAS MALA VISION CERCANA"
   Case "SINTOMAS DOLOR"
    opto_headers = "SINTOMAS DOLOR"
   Case "SINTOMAS MALA VISON LEJANA"
    opto_headers = "SINTOMAS MALA VISON LEJANA"
   Case "SINTOMAS SECRECION"
    opto_headers = "SINTOMAS SECRECION"
   Case "SINTOMAS CEFALEA"
    opto_headers = "SINTOMAS CEFALEA"
   Case "OTROS SINTOMAS"
    opto_headers = "OTROS SINTOMAS"
   Case "CABEZA - PARPADOS", "CABEZA PARPADOS"
    opto_headers = "CABEZA - PARPADOS"
   Case "CABEZA - PARPADOS OBS", "CABEZA PARPADOS OBS"
    opto_headers = "CABEZA - PARPADOS OBS"
   Case "CABEZA - CONJUNTIVAS", "CABEZA CONJUNTIVAS"
    opto_headers = "CABEZA - CONJUNTIVAS"
   Case "CABEZA - OBS CONJUNTIVAS", "CABEZA OBS CONJUNTIVAS"
    opto_headers = "CABEZA - OBS CONJUNTIVAS"
   Case "CABEZA - ESCLERAS", "CABEZA ESCLERAS"
    opto_headers = "CABEZA - ESCLERAS"
   Case "CABEZA - OBS ESCLERAS", "CABEZA OBS ESCLERAS"
    opto_headers = "CABEZA - OBS ESCLERAS"
   Case "CABEZA - PUPILAS", "CABEZA PUPILAS"
    opto_headers = "CABEZA - PUPILAS"
   Case "CABEZA - PUPILAS OBS", "CABEZA PUPILAS OBS"
    opto_headers = "CABEZA - PUPILAS OBS"
   Case "MOT/OCUL COVERT TEST LEJOS"
    opto_headers = "MOT/OCUL COVERT TEST LEJOS"
   Case "MOT/OCUL COVERT TEST CERCA"
    opto_headers = "MOT/OCUL COVERT TEST CERCA"
   Case "ESTADO DE CORRECCION"
    opto_headers = "ESTADO DE CORRECCION"
   Case "PATOLOGIA OCULAR"
    opto_headers = "PATOLOGIA OCULAR"
   Case "DIAG PPAL"
    opto_headers = "DIAG PPAL"
   Case "DIAG OBS"
    opto_headers = "DIAG OBS"
   Case "DIAG REL/1"
    opto_headers = "DIAG REL/1"
   Case "DIAG REL/2"
    opto_headers = "DIAG REL/2"
   Case "DIAG REL/3"
    opto_headers = "DIAG REL/3"
   Case "REC CORRECCION VISUAL PARA TRABAJAR"
    opto_headers = "REC CORRECCION VISUAL PARA TRABAJAR"
   Case "REC USO AR VIDEO TRMINAL"
    opto_headers = "REC USO AR VIDEO TRMINAL"
   Case "REC USO DE LENTES DE PROTECCION SOLAR"
    opto_headers = "REC USO DE LENTES DE PROTECCION SOLAR"
   Case "REC USO EPP VISUAL"
    opto_headers = "REC USO EPP VISUAL"
   Case "REC PAUSAS ACTIVAS"
    opto_headers = "REC PAUSAS ACTIVAS"
   Case "REC USO RX VISION PROXIMA"
    opto_headers = "REC USO RX VISION PROXIMA"
   Case "REC USO RX DESCANSO"
    opto_headers = "REC USO RX DESCANSO"
   Case "REC USO PERMANENTE RX OPTICA"
    opto_headers = "REC USO PERMANENTE RX OPTICA"
   Case "REC PYP"
    opto_headers = "REC PYP"
   Case "REC LUBRICANTE OCULAR"
    opto_headers = "REC LUBRICANTE OCULAR"
   Case "RECOMENDACIONES OBS"
    opto_headers = "RECOMENDACIONES OBS"
   Case "REM_ VALORACION OFTALM_"
    opto_headers = "REM_ VALORACION OFTALM_"
   Case "REM_ TOPOGRAFIA CORNEAL"
    opto_headers = "REM_ TOPOGRAFIA CORNEAL"
   Case "REM_ TRATAM_ ORTOPTICA"
    opto_headers = "REM_ TRATAM_ ORTOPTICA"
   Case "REM_ TEST FARNSWORTH"
    opto_headers = "REM_ TEST FARNSWORTH"
   Case "REALIZAR PRUEBA AMBULATORIA"
    opto_headers = "REALIZAR PRUEBA AMBULATORIA"
   Case "REMISIONES OBS"
    opto_headers = "REMISIONES OBS"
   Case "CONTROLES MENSUAL"
    opto_headers = "CONTROLES MENSUAL"
   Case "CONTROLES_BIMESTRALES"
    opto_headers = "CONTROLES_BIMESTRALES"
   Case "CONTROLES TRIMESTRAL"
    opto_headers = "CONTROLES TRIMESTRAL"
   Case "CONTROLES 6 MESES"
    opto_headers = "CONTROLES 6 MESES"
   Case "CONTROLES 1 A" & Chr(209) & "O"
    opto_headers = "CONTROLES 1 ANO"
   Case "CONTROLES CONFIRMATORIA"
    opto_headers = "CONTROLES CONFIRMATORIA"
   Case "ID_OPTOMETRIA"
    opto_headers = "ID_OPTOMETRIA"
   Case "OP_DIAGNOSTICO"
    opto_headers = "OP_DIAGNOSTICO"
   Case Else
    opto_headers = "SIN DATO"
  End Select
End Function

Public Function audio_headers(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "NROAIDENFICACION", "NRO IDENFICACION", "NRO IDENTIFICACION", "NRO IDENTFICACION"
    audio_headers = "NROAIDENFICACION"
   Case "TIPO EXAMEN"
    audio_headers = "TIPO EXAMEN"
   Case "EPP ESPECIFICO / AUDITIVO", "EPP"
    audio_headers = "EPP ESPECIFICO / AUDITIVO"
   Case "EPP ESPECIFICO / AUDITIVO COPA", "TIPO EPP"
    audio_headers = "EPP ESPECIFICO / AUDITIVO COPA"
   Case "EPP ESPECIFICO / AUDITIVO INSERCION"
    audio_headers = "EPP ESPECIFICO / AUDITIVO INSERCION"
   Case "EPP ESPECIFICO / AUDITIVO DOBLE"
    audio_headers = "EPP ESPECIFICO / AUDITIVO DOBLE"
   Case "PABELLON AURIC_ OIDO DER_","PABELLON AURIC  OIDO DER"
    audio_headers = "PABELLON AURIC_ OIDO DER_"
   Case "PABELLON AURIC_ OIDO DER_ OBS", "PABELLON AURIC  OIDO DER  OBS"
    audio_headers = "PABELLON AURIC_ OIDO DER_ OBS"
   Case "PABELLON AURIC_ OIDO IZQ_", "PABELLON AURIC  OIDO IZQ"
    audio_headers = "PABELLON AURIC_ OIDO IZQ_"
   Case "PABELLON AURIC_ OIDO IZQ_ OBS", "PABELLON AURIC  OIDO IZQ  OBS"
    audio_headers = "PABELLON AURIC_ OIDO IZQ_ OBS"
   Case "CONDUCTO AUDIT_ OIDO DER_", "CONDUCTO AUDIT  OIDO DER"
    audio_headers = "CONDUCTO AUDIT_ OIDO DER_"
   Case "CONDUCTO AUDIT_ OIDO DER_ OBS", "CONDUCTO AUDIT  OIDO DER  OBS"
    audio_headers = "CONDUCTO AUDIT_ OIDO DER_ OBS"
   Case "CONDUCTO AUDIT_ OIDO IZQ_", "CONDUCTO AUDIT  OIDO IZQ"
    audio_headers = "CONDUCTO AUDIT_ OIDO IZQ_"
   Case "CONDUCTO AUDIT_ OIDO IZQ_ OBS", "CONDUCTO AUDIT  OIDO IZQ  OBS"
    audio_headers = "CONDUCTO AUDIT_ OIDO IZQ_ OBS"
   Case "MEMBRANA TIMP_ OIDO DER", "MEMBRANA TIMP  OIDO DER"
    audio_headers = "MEMBRANA TIMP_ OIDO DER"
   Case "MEMBRANA TIMP_ OIDO DER_ OBS", "MEMBRANA TIMP  OIDO DER  OBS"
    audio_headers = "MEMBRANA TIMP_ OIDO DER_ OBS"
   Case "MEMBRANA TIMP_ OIDO IZQ", "MEMBRANA TIMP  OIDO IZQ"
    audio_headers = "MEMBRANA TIMP_ OIDO IZQ"
   Case "MEMBRANA TIMP_ OIDO IZQ_ OBS", "MEMBRANA TIMP  OIDO IZQ  OBS"
    audio_headers = "MEMBRANA TIMP_ OIDO IZQ_ OBS"
   Case "TIPO DE EXAMEN", "NOMBRE EXAMEN"
    audio_headers = "TIPO DE EXAMEN"
   Case "OD 500"
    audio_headers = "OD 500"
   Case "OD 1000"
    audio_headers = "OD 1000"
   Case "OD 2000"
    audio_headers = "OD 2000"
   Case "OD 3000"
    audio_headers = "OD 3000"
   Case "OD 4000"
    audio_headers = "OD 4000"
   Case "OD 6000"
    audio_headers = "OD 6000"
   Case "OD 8000"
    audio_headers = "OD 8000"
   Case "OI 500"
    audio_headers = "OI 500"
   Case "OI 1000"
    audio_headers = "OI 1000"
   Case "OI 2000"
    audio_headers = "OI 2000"
   Case "OI 3000"
    audio_headers = "OI 3000"
   Case "OI 4000"
    audio_headers = "OI 4000"
   Case "OI 6000"
    audio_headers = "OI 6000"
   Case "OI 8000"
    audio_headers = "OI 8000"
   Case "CONTROL SEGUN PVE"
    audio_headers = "CONTROL SEGUN PVE"
   Case "CONFIRMATORIA"
    audio_headers = "CONFIRMATORIA"
   Case "REMISION ORL"
    audio_headers = "REMISION ORL"
   Case "PRUEBAS COMPLEMENTARIAS"
    audio_headers = "PRUEBAS COMPLEMENTARIAS"
   Case "LIMPIEZA DE OIDO"
    audio_headers = "LIMPIEZA DE OIDO"
   Case "LIMPIEZA OD"
    audio_headers = "LIMPIEZA OD"
   Case "LIMPIEZA OI"
    audio_headers = "LIMPIEZA OI"
   Case "REPOSO AUDITIVO EXTRALAB"
    audio_headers = "REPOSO AUDITIVO EXTRALAB"
   Case "ROTAR DIADEMA TELEFONICA"
    audio_headers = "ROTAR DIADEMA TELEFONICA"
   Case "CONDUCIR CON VENTANAS CERRADAS"
    audio_headers = "CONDUCIR CON VENTANAS CERRADAS"
   Case "USO DE EPP AUDITIVO"
    audio_headers = "USO DE EPP AUDITIVO"
   Case "CONTROLES MENSUALES"
    audio_headers = "CONTROLES MENSUALES"
   Case "CONTROLES_BIMESTRALES","CONTROLES BIMESTRALES"
    audio_headers = "CONTROLES_BIMESTRALES"
   Case "CONTROLES TRIMESTRALES"
    audio_headers = "CONTROLES TRIMESTRALES"
   Case "CONTROLES 6 MESES"
    audio_headers = "CONTROLES 6 MESES"
   Case "CONTROLES 1 A" & Chr(209) & "O"
    audio_headers = "CONTROLES 1 ANO"
   Case "DIAG PPAL"
    audio_headers = "DIAG PPAL"
   Case "DIAG INTERNO"
    audio_headers = "DIAG INTERNO"
   Case "DIAG GATI-SO","DIAG GATISO","DIAG GATI SO"
    audio_headers = "DIAG GATI-SO"
   Case "ID_AUDIOMETRIA"
    audio_headers = "ID_AUDIOMETRIA"
   Case Else
    audio_headers = "SIN DATO"
  End Select
End Function

Public Function visio_headers(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "NRO IDENFICACION", "NRO IDENTIFICACION", "NRO IDENTIFICACION"
    visio_headers = "NRO IDENFICACION"
   Case "TIPO EXAMEN"
    visio_headers = "TIPO EXAMEN"
   Case "VISIO/ANT_ LABORAL ILUMINACION INADECUADA", "ANT_ LABORAL ILUMINACION INADECUADA"
    visio_headers = "VISIO/ANT_ LABORAL ILUMINACION INADECUADA"
   Case "VISIO/ANT_ LABORALVISIO RADIACIONES UV", "ANT_ LABORALVISIO RADIACIONES UV"
    visio_headers = "VISIO/ANT_ LABORALVISIO RADIACIONES UV"
   Case "VISIO/ANT_ LABORAL MALA VENTILACION", "ANT_ LABORAL MALA VENTILACION"
    visio_headers = "VISIO/ANT_ LABORAL MALA VENTILACION"
   Case "VISIO/ANT_ LABORAL GASES TOXICOS", "ANT_ LABORAL GASES TOXICOS"
    visio_headers = "VISIO/ANT_ LABORAL GASES TOXICOS"
   Case "SINTOMAS FOTOFOBIA"
    visio_headers = "SINTOMAS FOTOFOBIA"
   Case "SINTOMAS OJO ROJO"
    visio_headers = "SINTOMAS OJO ROJO"
   Case "SINTOMAS LAGRIMEO"
    visio_headers = "SINTOMAS LAGRIMEO"
   Case "SINTOMAS VISION BORROSA"
    visio_headers = "SINTOMAS VISION BORROSA"
   Case "SINTOMAS ARDOR"
    visio_headers = "SINTOMAS ARDOR"
   Case "SINTOMAS VISION DOBLE"
    visio_headers = "SINTOMAS VISION DOBLE"
   Case "SINTOMAS CANSANCIO"
    visio_headers = "SINTOMAS CANSANCIO"
   Case "SINTOMAS MALA VISION CERCANA"
    visio_headers = "SINTOMAS MALA VISION CERCANA"
   Case "SINTOMAS DOLOR"
    visio_headers = "SINTOMAS DOLOR"
   Case "SINTOMAS MALA VISON LEJANA"
    visio_headers = "SINTOMAS MALA VISON LEJANA"
   Case "SINTOMAS SECRECION"
    visio_headers = "SINTOMAS SECRECION"
   Case "SINTOMAS CEFALEA"
    visio_headers = "SINTOMAS CEFALEA"
   Case "OTROS SINTOMAS"
    visio_headers = "OTROS SINTOMAS"
   Case "CABEZA - PARPADOS","CABEZA PARPADOS"
    visio_headers = "CABEZA - PARPADOS"
   Case "CABEZA - PARPADOS OBS","CABEZA PARPADOS OBS"
    visio_headers = "CABEZA - PARPADOS OBS"
   Case "CABEZA - CONJUNTIVAS","CABEZA CONJUNTIVAS"
    visio_headers = "CABEZA - CONJUNTIVAS"
   Case "CABEZA - OBS CONJUNTIVAS","CABEZA OBS CONJUNTIVAS"
    visio_headers = "CABEZA - OBS CONJUNTIVAS"
   Case "CABEZA - ESCLERAS","CABEZA ESCLERAS"
    visio_headers = "CABEZA - ESCLERAS"
   Case "CABEZA - OBS ESCLERAS","CABEZA OBS ESCLERAS"
    visio_headers = "CABEZA - OBS ESCLERAS"
   Case "CABEZA - PUPILAS","CABEZA PUPILAS"
    visio_headers = "CABEZA - PUPILAS"
   Case "CABEZA - PUPILAS OBS","CABEZA PUPILAS OBS"
    visio_headers = "CABEZA - PUPILAS OBS"
   Case "IMP/DIAG VL0OD NORMAL", "IMP/DIAG VL-OD NORMAL", "IMP/DIAG VL OD NORMAL"
    visio_headers = "IMP/DIAG VL0OD NORMAL"
   Case "IMP/DIAG VL0OI NORMAL", "IMP/DIAG VL-OI NORMAL", "IMP/DIAG VL OI NORMAL"
    visio_headers = "IMP/DIAG VL0OI NORMAL"
   Case "IMP/DIAG VP0OD NORMAL", "IMP/DIAG VP-OD NORMAL", "IMP/DIAG VP OD NORMAL"
    visio_headers = "IMP/DIAG VP0OD NORMAL"
   Case "IMP/DIAG VP0OI NORMAL", "IMP/DIAG VP-OI NORMAL", "IMP/DIAG VP OI NORMAL"
    visio_headers = "IMP/DIAG VP0OI NORMAL"
   Case "IMP/DIAG VL0OD DISMINUIDO", "IMP/DIAG VL-OD DISMINUIDO", "IMP/DIAG VL OD DISMINUIDO"
    visio_headers = "IMP/DIAG VL0OD DISMINUIDO"
   Case "IMP/DIAG VL0OI DISMINUIDO", "IMP/DIAG VL-OI DISMINUIDO", "IMP/DIAG VL OI DISMINUIDO"
    visio_headers = "IMP/DIAG VL0OI DISMINUIDO"
   Case "IMP/DIAG VP0OD DISMINUIDO", "IMP/DIAG VP-OD DISMINUIDO", "IMP/DIAG VP OD DISMINUIDO"
    visio_headers = "IMP/DIAG VP0OD DISMINUIDO"
   Case "IMP/DIAG VP0OI DISMINUIDO", "IMP/DIAG VP-OI DISMINUIDO", "IMP/DIAG VP OI DISMINUIDO"
    visio_headers = "IMP/DIAG VP0OI DISMINUIDO"
   Case "IMP/DIAG VL0OD NORMAL RX", "IMP/DIAG VL-OD NORMAL RX", "IMP/DIAG VL OD NORMAL RX"
    visio_headers = "IMP/DIAG VL0OD NORMAL RX"
   Case "IMP/DIAG VL0OI NORMAL RX", "IMP/DIAG VL-OI NORMAL RX", "IMP/DIAG VL OI NORMAL RX"
    visio_headers = "IMP/DIAG VL0OI NORMAL RX"
   Case "IMP/DIAG VP0OD NORMAL RX", "IMP/DIAG VP-OD NORMAL RX", "IMP/DIAG VP OD NORMAL RX"
    visio_headers = "IMP/DIAG VP0OD NORMAL RX"
   Case "IMP/DIAG VP0OI NORMAL RX", "IMP/DIAG VP-OI NORMAL RX", "IMP/DIAG VP OI NORMAL RX"
    visio_headers = "IMP/DIAG VP0OI NORMAL RX"
   Case "IMP/DIAG VL0OD DISMINUIDO RX", "IMP/DIAG VL-OD DISMINUIDO RX", "IMP/DIAG VL OD DISMINUIDO RX"
    visio_headers = "IMP/DIAG VL0OD DISMINUIDO RX"
   Case "IMP/DIAG VL0OI DISMINUIDO RX", "IMP/DIAG VL-OI DISMINUIDO RX", "IMP/DIAG VL OI DISMINUIDO RX"
    visio_headers = "IMP/DIAG VL0OI DISMINUIDO RX"
   Case "IMP/DIAG VP0OD DISMINUIDO RX", "IMP/DIAG VP-OD DISMINUIDO RX", "IMP/DIAG VP OD DISMINUIDO RX"
    visio_headers = "IMP/DIAG VP0OD DISMINUIDO RX"
   Case "IMP/DIAG VP0OI DISMINUIDO RX", "IMP/DIAG VP-OI DISMINUIDO RX", "IMP/DIAG VP OI DISMINUIDO RX"
    visio_headers = "IMP/DIAG VP0OI DISMINUIDO RX"
   Case "RESULTADO VISIO"
    visio_headers = "RESULTADO VISIO"
   Case "IMP/DIAG OBS"
    visio_headers = "IMP/DIAG OBS"
   Case "REC CORRECCION VISUAL PARA TRABAJAR"
    visio_headers = "REC CORRECCION VISUAL PARA TRABAJAR"
   Case "REC USO RX PARA VISION PROX"
    visio_headers = "REC USO RX PARA VISION PROX"
   Case "REC USO AR VIDEO TRMINAL","REC USO AR VIDEO TERMINAL"
    visio_headers = "REC USO AR VIDEO TRMINAL"
   Case "REC USO RX DESCANSO"
    visio_headers = "REC USO RX DESCANSO"
   Case "REC USO LENTES PROT_ SOLAR","REC USO LENTES PROTECCION SOLAR"
    visio_headers = "REC USO LENTES PROT_ SOLAR"
   Case "REC USO PERMANENTE RX OPTICA"
    visio_headers = "REC USO PERMANENTE RX OPTICA"
   Case "REC USO EPP VISUAL"
    visio_headers = "REC USO EPP VISUAL"
   Case "REC PYP"
    visio_headers = "REC PYP"
   Case "REC PAUSAS ACTIVAS"
    visio_headers = "REC PAUSAS ACTIVAS"
   Case "REC LUBRICANTE OCULAR"
    visio_headers = "REC LUBRICANTE OCULAR"
   Case "RECOMENDACIONES OBS"
    visio_headers = "RECOMENDACIONES OBS"
   Case "REM_ VALORACION OFTALM_"
    visio_headers = "REM_ VALORACION OFTALM_"
   Case "REM_ VALORACION OPTO_ COMPLETA"
    visio_headers = "REM_ VALORACION OPTO_ COMPLETA"
   Case "REM_ TOPOGRAFIA CORNEAL"
    visio_headers = "REM_ TOPOGRAFIA CORNEAL"
   Case "REM_ TRATAM_ ORTOPTICA"
    visio_headers = "REM_ TRATAM_ ORTOPTICA"
   Case "REM_ TEST FARNSWORTH"
    visio_headers = "REM_ TEST FARNSWORTH"
   Case "REALIZAR PRUEBA AMBULATORIA"
    visio_headers = "REALIZAR PRUEBA AMBULATORIA"
   Case "OTRAS REMISIONES"
    visio_headers = "OTRAS REMISIONES"
   Case "CONTROL MENSUAL", "CONTROLES"
    visio_headers = "CONTROL MENSUAL"
   Case "CONTROLES_BIMESTRALES"
    visio_headers = "CONTROLES_BIMESTRALES"
   Case "CONTROL TRIMESTRAL", "CONTROLES TRIMESTRAL"
    visio_headers = "CONTROL TRIMESTRAL"
   Case "CONTROL 6 MESES", "CONTROLES SEMESTRAL"
    visio_headers = "CONTROL 6 MESES"
   Case "CONTROL 1 A" & Chr(209) & "O", "CONTROLES ANUAL"
    visio_headers = "CONTROL 1 ANO"
   Case "CONTROL CONFIRMATORIA", "CONTROLES CONFIRMATORIA"
    visio_headers = "CONTROL CONFIRMATORIA"
   Case "ID_VISIOMETRIA"
    visio_headers = "ID_VISIOMETRIA"
   Case Else
    visio_headers = "SIN DATO"
  End Select
End Function

Public Function espiro_headers(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "NRO IDENFICACION", "NRO IDENTIFICACION"
    espiro_headers = "NRO IDENFICACION"
   Case "TIPO EXAMEN"
    espiro_headers = "TIPO EXAMEN"
   Case "ALERGIAS"
    espiro_headers = "ALERGIAS"
   Case "ALERGIAS OBS","ALERGIAS_DESC"
    espiro_headers = "ALERGIAS OBS"
   Case "TUBERCULOSIS","TUBERCULOSIS DESC"
    espiro_headers = "TUBERCULOSIS"
   Case "TOS CRONICA","TOS_CRONICA_DESC"
    espiro_headers = "TOS CRONICA"
   Case "GRIPAS FRECUENTES","GRIPAS_FRECUENTES_DESC"
    espiro_headers = "GRIPAS FRECUENTES"
   Case "FARINGITIS","FARINGITIS_DESC"
    espiro_headers = "FARINGITIS"
   Case "FARINGOAMIGDALITIS","FARINGOAMIGDALITIS_DESC"
    espiro_headers = "FARINGOAMIGDALITIS"
   Case "RINITIS","RINITIS_DESC"
    espiro_headers = "RINITIS"
   Case "SINUSITIS","SINUSITIS_DESC"
    espiro_headers = "SINUSITIS"
   Case "CX TORAX","CIRUGIA_TORAX"
    espiro_headers = "CX TORAX"
   Case "CX TORAX OBS","CIRUGIA_TORAX_DESC"
    espiro_headers = "CX TORAX OBS"
   Case "ASMA BRONQUIAL","ASMA_BRONQUIAL_DESC"
    espiro_headers = "ASMA BRONQUIAL"
   Case "BRONQUITIS","BRONQUITIS_DESC"
    espiro_headers = "BRONQUITIS"
   Case "NEUMONIA","NEUMONIA_DESC"
    espiro_headers = "NEUMONIA"
   Case "TRAUMA COSTAL","TRAUMA_COSTAL_DESC"
    espiro_headers = "TRAUMA COSTAL"
   Case "CANCER"
    espiro_headers = "CANCER"
   Case "CANCER OBS","CANCER_DESC"
    espiro_headers = "CANCER OBS"
   Case "OTROS RESPIRATORIOS"
    espiro_headers = "OTROS RESPIRATORIOS"
   Case "RIESGO QUIMICO / POLVOS","RIESGO_QCO/POLVOS"
    espiro_headers = "RIESGO QUIMICO / POLVOS"
   Case "RIESGO QUIMICO / FIBRAS"
    espiro_headers = "RIESGO QUIMICO / FIBRAS"
   Case "RIESGO QUIMICO / LIQUIDOS"
    espiro_headers = "RIESGO QUIMICO / LIQUIDOS"
   Case "RIESGO QUIMICO /GASES"
    espiro_headers = "RIESGO QUIMICO /GASES"
   Case "RIESGO QUIMICO / VAPORES"
    espiro_headers = "RIESGO QUIMICO / VAPORES"
   Case "RIESGO QUIMICO / HUMOS","RIESGO_QCO/HUMOS"
    espiro_headers = "RIESGO QUIMICO / HUMOS"
   Case "RIESGO QUIMICO /MATERIAL PARTICULADO", "RIESGO QUIMICO  MATERIAL PARTICULADO"
    espiro_headers = "RIESGO QUIMICO /MATERIAL PARTICULADO"
   Case "OTROS RIESGOS QUIMICOS"
    espiro_headers = "OTROS RIESGOS QUIMICOS"
   Case "EPP ESPECIFICO / TAPABOCA"
    espiro_headers = "EPP ESPECIFICO / TAPABOCA"
   Case "EPP ESPECIFICO / RESPIRADOR"
    espiro_headers = "EPP ESPECIFICO / RESPIRADOR"
   Case "ACT_ FISICA","ACTIVIDAD_FISICA"
    espiro_headers = "ACT_ FISICA"
   Case "FUMA"
    espiro_headers = "FUMA"
   Case "CIGARRILLOS DIA"
    espiro_headers = "CIGARRILLOS DIA"
   Case "FRECUENCIA"
    espiro_headers = "FRECUENCIA"
   Case "TIEMPO EN A" & Chr(209) & "OS"
    espiro_headers = "TIEMPO EN ANOS"
   Case "INTERPRETACION"
    espiro_headers = "INTERPRETACION"
   Case "PESO"
    espiro_headers = "PESO"
   Case "TALLA"
    espiro_headers = "TALLA"
   Case "FVC PRED DIAG_"
    espiro_headers = "FVC PRED DIAG_"
   Case "FVC %TEOR DIAG_"
    espiro_headers = "FVC %TEOR DIAG_"
   Case "FEV1 PRED DIAG_"
    espiro_headers = "FEV1 PRED DIAG_"
   Case "FEV1 %TEOR DIAG_"
    espiro_headers = "FEV1 %TEOR DIAG_"
   Case "FEV1/FVC PRED DIAG_"
    espiro_headers = "FEV1/FVC PRED DIAG_"
   Case "FEV1/FVC %TEOR DIAG_"
    espiro_headers = "FEV1/FVC %TEOR DIAG_"
   Case "PEF PRED DIAG_"
    espiro_headers = "PEF PRED DIAG_"
   Case "PEF %TEOR DIAG_"
    espiro_headers = "PEF %TEOR DIAG_"
   Case "FEF 25-75 PRED DIAG_","FEF 25 75 PRED DIAG_"
    espiro_headers = "FEF 25-75 PRED DIAG_"
   Case "FEF 25-75 %TEOR DIAG_", "FEF 25 75 %TEOR DIAG_"
    espiro_headers = "FEF 25-75 %TEOR DIAG_"
   Case "DIAG_ PPAL","DIAG_PPAL"
    espiro_headers = "DIAG_ PPAL"
   Case "DIAG_ OBS"
    espiro_headers = "DIAG_ OBS"
   Case "DIAG_ REL/1"
    espiro_headers = "DIAG_ REL/1"
   Case "DIAG_ REL/2"
    espiro_headers = "DIAG_ REL/2"
   Case "DIAG_ REL/3"
    espiro_headers = "DIAG_ REL/3"
   Case "TIPO_INTERPRETACION"
    espiro_headers = "TIPO_INTERPRETACION"
   Case "TIPO_GRADO"
    espiro_headers = "TIPO_GRADO"
   Case "RESULTADO_ESPIROMETRIA"
    espiro_headers = "RESULTADO_ESPIROMETRIA"
   Case "REC/GRALES DEJAR DE FUMAR"
    espiro_headers = "REC/GRALES DEJAR DE FUMAR"
   Case "REC/GRALES CONTINUAR CONTROLES EPS"
    espiro_headers = "REC/GRALES CONTINUAR CONTROLES EPS"
   Case "REC/GRALES BAJAR DE PESO"
    espiro_headers = "REC/GRALES BAJAR DE PESO"
   Case "REC/GRALES TOMAR RAYOS X TORAX"
    espiro_headers = "REC/GRALES TOMAR RAYOS X TORAX"
   Case "REC/GRALES REALIZAR EJERC_ 3X SEMANA"
    espiro_headers = "REC/GRALES REALIZAR EJERC_ 3X SEMANA"
   Case "REC/GRALES VALORAC_ EPS X NEUMOLOGIA"
    espiro_headers = "REC/GRALES VALORAC_ EPS X NEUMOLOGIA"
   Case "REC/LAB UTILIZAR EPR"
    espiro_headers = "REC/LAB UTILIZAR EPR"
   Case "REC/LAB INGRESAR SVE"
    espiro_headers = "REC/LAB INGRESAR SVE"
   Case "CONTROLES MENSUAL","CONTROLES","CONTROLES_MENSUALES"
    espiro_headers = "CONTROLES MENSUAL"
   Case "CONTROLES_BIMESTRALES"
    espiro_headers = "CONTROLES_BIMESTRALES"
   Case "CONTROLES TRIMESTRAL"
    espiro_headers = "CONTROLES TRIMESTRAL"
   Case "CONTROLES SEMESTRAL"
    espiro_headers = "CONTROLES SEMESTRAL"
   Case "CONTROLES ANUAL"
    espiro_headers = "CONTROLES ANUAL"
   Case "CONTROLES CONFIRMATORIA"
    espiro_headers = "CONTROLES CONFIRMATORIA"
   Case "TECNICA ACEPTABLE"
    espiro_headers = "TECNICA ACEPTABLE"
   Case "ID_ESPIROMETRIA"
    espiro_headers = "ID_ESPIROMETRIA"
   Case Else
    espiro_headers = "SIN DATO"
  End Select
End Function

Public Function osteo_headers(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "NRO IDENFICACION", "NRO IDENTIFICACION"
    osteo_headers = "NRO IDENFICACION"
   Case "TIPO EXAMEN"
    osteo_headers = "TIPO EXAMEN"
   Case "CERVICALGIA"
    osteo_headers = "CERVICALGIA"
   Case "CERVICALGIA OBS"
    osteo_headers = "CERVICALGIA OBS"
   Case "EPICONDILITIS"
    osteo_headers = "EPICONDILITIS"
   Case "EPICONDILITIS OBS"
    osteo_headers = "EPICONDILITIS OBS"
   Case "LUMBALGIA"
    osteo_headers = "LUMBALGIA"
   Case "LUMBALGIA OBS"
    osteo_headers = "LUMBALGIA OBS"
   Case "S_ TUNEL CARPO"
    osteo_headers = "S_ TUNEL CARPO"
   Case "S_ TUNEL CARPO OBS"
    osteo_headers = "S_ TUNEL CARPO OBS"
   Case "FRACTURAS"
    osteo_headers = "FRACTURAS"
   Case "FRACTURAS OBS"
    osteo_headers = "FRACTURAS OBS"
   Case "TENDINITIS"
    osteo_headers = "TENDINITIS"
   Case "TENDINITIS OBS"
    osteo_headers = "TENDINITIS OBS"
   Case "LESION EN MENISCOS OBS", "LE1ON EN MENISCOS OBS"
    osteo_headers = "LESION EN MENISCOS OBS"
   Case "LESION EN MENISCOS"
    osteo_headers = "LESION EN MENISCOS"
   Case "ESGUINCES"
    osteo_headers = "ESGUINCES"
   Case "ESGUINCES OBS"
    osteo_headers = "ESGUINCES OBS"
   Case "HOMBRO DOLOROSO"
    osteo_headers = "HOMBRO DOLOROSO"
   Case "HOMBRO DOLOROSO OBS"
    osteo_headers = "HOMBRO DOLOROSO OBS"
   Case "RADICULOPATIA"
    osteo_headers = "RADICULOPATIA"
   Case "RADICULOPATIA OBS"
    osteo_headers = "RADICULOPATIA OBS"
   Case "BURSITIS"
    osteo_headers = "BURSITIS"
   Case "BURSITIS OBS"
    osteo_headers = "BURSITIS OBS"
   Case "ARTROSIS"
    osteo_headers = "ARTROSIS"
   Case "ARTROSIS OBS"
    osteo_headers = "ARTROSIS OBS"
   Case "ESCOLIOSIS"
    osteo_headers = "ESCOLIOSIS"
   Case "ESCOLIOSIS OBS"
    osteo_headers = "ESCOLIOSIS OBS"
   Case "RETRACCIONES MUSCULARES"
    osteo_headers = "RETRACCIONES MUSCULARES"
   Case "RETRACCIONES MUSCULARES OBS"
    osteo_headers = "RETRACCIONES MUSCULARES OBS"
   Case "MALFORMACIONES"
    osteo_headers = "MALFORMACIONES"
   Case "MALFORMACIONES OBS"
    osteo_headers = "MALFORMACIONES OBS"
   Case "DISCOPATIAS"
    osteo_headers = "DISCOPATIAS"
   Case "DISCOPATIAS OBS"
    osteo_headers = "DISCOPATIAS OBS"
   Case "FIBROMALGIA"
    osteo_headers = "FIBROMALGIA"
   Case "FIBROMALGIA OBS"
    osteo_headers = "FIBROMALGIA OBS"
   Case "OTROS ANT_ OSTEOMUSCULARES"
    osteo_headers = "OTROS ANT_ OSTEOMUSCULARES"
   Case "PESO"
    osteo_headers = "PESO"
   Case "TALLA"
    osteo_headers = "TALLA"
   Case "DIAG_ PPAL"
    osteo_headers = "DIAG_ PPAL"
   Case "DIAG_ PPAL OBS"
    osteo_headers = "DIAG_ PPAL OBS"
   Case "DIAG_ REL 1"
    osteo_headers = "DIAG_ REL 1"
   Case "DIAG_ REL 2"
    osteo_headers = "DIAG_ REL 2"
   Case "DIAG_ REL 3"
    osteo_headers = "DIAG_ REL 3"
   Case "REC/PERS ACT_ FISICA CARDIO 3X/SEMANA", "REC/PERS ACT_ FI1CA CARDIO 3X/SEMANA"
    osteo_headers = "REC/PERS ACT_ FISICA CARDIO 3X/SEMANA"
   Case "REC/PERS FORT_ 15 REPETICIONES/3 SERIES"
    osteo_headers = "REC/PERS FORT_ 15 REPETICIONES/3 SERIES"
   Case "REC/PERS EJERC_ ESTIRAMIENTO 20 SEG"
    osteo_headers = "REC/PERS EJERC_ ESTIRAMIENTO 20 SEG"
   Case "REC/PERS AUTOCUIDADO"
    osteo_headers = "REC/PERS AUTOCUIDADO"
   Case "REC/PERS SEGUIMIENTO MEDICO"
    osteo_headers = "REC/PERS SEGUIMIENTO MEDICO"
   Case "REC/OCUP SVE PREVENSION LESIONES", "REC/OCUP SVE PREVEN1ON LE1ONES"
    osteo_headers = "REC/OCUP SVE PREVENSION LESIONES"
   Case "REC/OCUP MANIPULACION DE CARGA"
    osteo_headers = "REC/OCUP MANIPULACION DE CARGA"
   Case "REC/OCUP PAUSAS ACTIVAS"
    osteo_headers = "REC/OCUP PAUSAS ACTIVAS"
   Case "REC/OCUP ANALISIS ERGONOMICOS", "REC/OCUP ANALI1S ERGO0MICOS"
    osteo_headers = "REC/OCUP ANALISIS ERGONOMICOS"
   Case "REC/OCUP EVITAR POSTURAS FORZADAS"
    osteo_headers = "REC/OCUP EVITAR POSTURAS FORZADAS"
   Case "RECOM_ OCUPACIONALES"
    osteo_headers = "RECOM_ OCUPACIONALES"
   Case "RECOM_ G/RALES"
    osteo_headers = "RECOM_ G/RALES"
   Case "ID_OSTEOMUSCULAR"
    osteo_headers = "ID_OSTEOMUSCULAR"
   Case Else
    osteo_headers = "SIN DATO"
  End Select
End Function

Public Function comple_headers(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "NRO IDENFICACION", "NRO IDENTIFICACION"
    comple_headers = "NRO IDENFICACION"
   Case "TIPO EXAMEN"
    comple_headers = "TIPO EXAMEN"
   Case "PROCEDIMIENTO"
    comple_headers = "PROCEDIMIENTO"
   Case "DIAG_ PPAL"
    comple_headers = "DIAG_ PPAL"
   Case "DIAG_ PPAL OBS"
    comple_headers = "DIAG_ PPAL OBS"
   Case "DIAG_ REL/1"
    comple_headers = "DIAG_ REL/1"
   Case "DIAG_ REL/2"
    comple_headers = "DIAG_ REL/2"
   Case "DIAG_ REL/3"
    comple_headers = "DIAG_ REL/3"
   Case "HALLAZGOS","HALLAZGO"
    comple_headers = "HALLAZGOS"
   Case "ID_COMPLEMENTARIOS"
    comple_headers = "ID_COMPLEMENTARIOS"
   Case Else
    comple_headers = "SIN DATO"
  End Select
End Function

Public Function psicotecnica_headers(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "NRO IDENFICACION", "NRO IDENTIFICACION"
    psicotecnica_headers = "NRO IDENFICACION"
   Case "TIPO EXAMEN"
    psicotecnica_headers = "TIPO EXAMEN"
   Case "PACIENTE"
    psicotecnica_headers = "PACIENTE"
   Case "PRUEBA PSICOTECNICA"
    psicotecnica_headers = "PRUEBA PSICOTECNICA"
   Case "DIAGNOSTICO PPAL (CUMPLE, NO CUMPLE)", "DIAGNOSTICO PPAL"
    psicotecnica_headers = "DIAGNOSTICO PPAL (CUMPLE, NO CUMPLE)"
   Case "DIAGNOSTICO OBS"
    psicotecnica_headers = "DIAGNOSTICO OBS"
   Case "ID_PSICOTECNICA"
    psicotecnica_headers = "ID_PSICOTECNICA"
   Case Else
    psicotecnica_headers = "SIN DATO"
  End Select
End Function

Public Function psicosensometrica_headers(ByVal value As String) As String
  Select Case Trim(UCase(value))
   Case "NRO IDENFICACION", "NRO IDENTIFICACION"
    psicosensometrica_headers = "NRO IDENFICACION"
   Case "TIPO EXAMEN"
    psicosensometrica_headers = "TIPO EXAMEN"
   Case "PACIENTE"
    psicosensometrica_headers = "PACIENTE"
   Case "PRUEBA PSICOSENSOMETRICA"
    psicosensometrica_headers = "PRUEBA PSICOSENSOMETRICA"
   Case "DIAGNOSTICO PPAL"
    psicosensometrica_headers = "DIAGNOSTICO PPAL"
   Case "DIAGNOSTICO OBS"
    psicosensometrica_headers = "DIAGNOSTICO OBS"
   Case "DIAGNOSTICO REL/1"
    psicosensometrica_headers = "DIAGNOSTICO REL/1"
   Case "DIAGNOSTICO REL/2"
    psicosensometrica_headers = "DIAGNOSTICO REL/2"
   Case "DIAGNOSTICO REL/3"
    psicosensometrica_headers = "DIAGNOSTICO REL/3"
   Case "CONTROLES MENSUALES"
    psicosensometrica_headers = "CONTROLES MENSUALES"
   Case "CONTROLES BIMENSUAL"
    psicosensometrica_headers = "CONTROLES BIMENSUAL"
   Case "CONTROLES TRIMESTRALES"
    psicosensometrica_headers = "CONTROLES TRIMESTRALES"
   Case "CONTROLES 6 MESES"
    psicosensometrica_headers = "CONTROLES 6 MESES"
   Case "CONTROLES 1 A" & Chr(209) & "O"
    psicosensometrica_headers = "CONTROLES 1 ANO"
   Case "CONTROLES CONFIRMATORIA"
    psicosensometrica_headers = "CONTROLES CONFIRMATORIA"
   Case "ID_PSICOSENSOMETRICA"
    psicosensometrica_headers = "ID_PSICOSENSOMETRICA"
   Case Else
    psicosensometrica_headers = "SIN DATO"
  End Select
End Function
