Attribute VB_Name = "config_osteo"
'namespace=vba-files\Module\configs
Option Explicit

Public Sub configOsteo()
  '
  ' configOsteo: realiza la configuracion inicial de las cabeceras asi como el nombre de la tabla
  '
  '
  range("A3") = "NRO IDENFICACION"
  range("B3") = "CERVICALGIA"
  range("C3") = "CERVICALGIA OBS"
  range("D3") = "EPICONDILITIS"
  range("E3") = "EPICONDILITIS OBS"
  range("F3") = "LUMBALGIA"
  range("G3") = "LUMBALGIA OBS"
  range("H3") = "S_ TUNEL CARPO"
  range("I3") = "S_ TUNEL CARPO OBS"
  range("J3") = "FRACTURAS"
  range("K3") = "FRACTURAS OBS"
  range("L3") = "TENDINITIS"
  range("M3") = "TENDINITIS OBS"
  range("N3") = "LESION EN MENISCOS OBS"
  range("O3") = "LESION EN MENISCOS"
  range("P3") = "ESGUINCES"
  range("Q3") = "ESGUINCES OBS"
  range("R3") = "HOMBRO DOLOROSO"
  range("S3") = "HOMBRO DOLOROSO OBS"
  range("T3") = "RADICULOPATIA"
  range("U3") = "RADICULOPATIA OBS"
  range("V3") = "BURSITIS"
  range("W3") = "BURSITIS OBS"
  range("X3") = "ARTROSIS"
  range("Y3") = "ARTROSIS OBS"
  range("Z3") = "ESCOLIOSIS"
  range("AA3") = "ESCOLIOSIS OBS"
  range("AB3") = "RETRACCIONES MUSCULARES"
  range("AC3") = "RETRACCIONES MUSCULARES OBS"
  range("AD3") = "MALFORMACIONES"
  range("AE3") = "MALFORMACIONES OBS"
  range("AF3") = "DISCOPATIAS"
  range("AG3") = "DISCOPATIAS OBS"
  range("AH3") = "FIBROMALGIA"
  range("AI3") = "FIBROMALGIA OBS"
  range("AJ3") = "OTROS ANT_ OSTEOMUSCULARES"
  range("AK3") = "PESO"
  range("AL3") = "TALLA"
  range("AM3") = "IMC"
  range("AN3") = "CLASIFICACION IMC"
  range("AO3") = "DIAG_ PPAL"
  range("AP3") = "DIAG_ PPAL OBS"
  range("AQ3") = "DIAG_ REL 1"
  range("AR3") = "DIAG_ REL 2"
  range("AS3") = "DIAG_ REL 3"
  range("AT3") = "REC/PERS ACT_ FISICA CARDIO 3X/SEMANA"
  range("AU3") = "REC/PERS FORT_ 15 REPETICIONES/3 SERIES"
  range("AV3") = "REC/PERS EJERC_ ESTIRAMIENTO 20 SEG"
  range("AW3") = "REC/PERS AUTOCUIDADO"
  range("AX3") = "REC/PERS SEGUIMIENTO MEDICO"
  range("AY3") = "REC/OCUP SVE PREVENSION LESIONES"
  range("AZ3") = "REC/OCUP MANIPULACION DE CARGA"
  range("BA3") = "REC/OCUP PAUSAS ACTIVAS"
  range("BB3") = "REC/OCUP ANALISIS ERGONOMICOS"
  range("BC3") = "REC/OCUP EVITAR POSTURAS FORZADAS"
  range("BD3") = "RECOM_ OCUPACIONALES"
  range("BE3") = "RECOM_ G/RALES"
  range("BF3") = "emo_id(orden_lista_trabajadoresid)"
  range("BG3") = "ID_OSTEOMUSCULAR"
  range("BH3") = "SCRIPT osteomuscular"
  range("BI3") = "SCRIPT osteo_antecedentes_pivot"
  range("BJ3") = "SCRIPT osteo_cie_pivot"
  range("BK3") = "SCRIPT osteo_recomendaciones_pivot"
  ActiveSheet.ListObjects.Add(xlSrcRange, range("$A$3:$BK$4"), , xlYes).Name = _
  "tbl_osteo"
  ActiveSheet.ListObjects("tbl_osteo").TableStyle = "TableStyleLight9"

  range("tbl_osteo[[#Headers],[IMC]:[CLASIFICACION IMC]]").Style = "Neutral"
  range("tbl_osteo[[#Data],[IMC]:[CLASIFICACION IMC]]").Style = "Notas"
  range("tbl_osteo[[#Headers],[emo_id(orden_lista_trabajadoresid)]]").Style = "Neutral"
  range("tbl_osteo[[#Data],[emo_id(orden_lista_trabajadoresid)]]").Style = "Notas"
  range("tbl_osteo[[#Headers],[SCRIPT osteomuscular]:[SCRIPT osteo_recomendaciones_pivot]]").Style = "Celda de comprobaci" & ChrW(243) & "n"
  range("tbl_osteo[[#Data],[SCRIPT osteomuscular]:[SCRIPT osteo_recomendaciones_pivot]]").Style = "Salida"
  
  Call formatTable("tbl_osteo")
  
End Sub

