Attribute VB_Name = "config_espiro"
'namespace=vba-files\Module\configs
Option Explicit

Public Sub configEspiro()
  '
  ' configEspiro: realiza la configuracion inicial de las cabeceras asi como el nombre de la tabla
  '
  '
  range("A3") = "NRO IDENFICACION"
  range("B3") = "ALERGIAS"
  range("C3") = "ALERGIAS OBS"
  range("D3") = "TUBERCULOSIS"
  range("E3") = "TOS CRONICA"
  range("F3") = "GRIPAS FRECUENTES"
  range("G3") = "FARINGITIS"
  range("H3") = "FARINGOAMIGDALITIS"
  range("I3") = "RINITIS"
  range("J3") = "SINUSITIS"
  range("K3") = "CX TORAX"
  range("L3") = "CX TORAX OBS"
  range("M3") = "ASMA BRONQUIAL"
  range("N3") = "BRONQUITIS"
  range("O3") = "NEUMONIA"
  range("P3") = "TRAUMA COSTAL"
  range("Q3") = "CANCER"
  range("R3") = "CANCER OBS"
  range("S3") = "OTROS RESPIRATORIOS"
  range("T3") = "RIESGO QUIMICO / POLVOS"
  range("U3") = "RIESGO QUIMICO / FIBRAS"
  range("V3") = "RIESGO QUIMICO / LIQUIDOS"
  range("W3") = "RIESGO QUIMICO /GASES"
  range("X3") = "RIESGO QUIMICO / VAPORES"
  range("Y3") = "RIESGO QUIMICO / HUMOS"
  range("Z3") = "RIESGO QUIMICO /MATERIAL PARTICULADO"
  range("AA3") = "OTROS RIESGOS QUIMICOS"
  range("AB3") = "EPP ESPECIFICO / TAPABOCA"
  range("AC3") = "EPP ESPECIFICO / RESPIRADOR"
  range("AD3") = "ACT_ FISICA"
  range("AE3") = "FUMA"
  range("AF3") = "CIGARRILLOS DIA"
  range("AG3") = "FRECUENCIA"
  range("AH3") = "TIEMPO EN A" & ChrW(209) & "OS"
  range("AI3") = "INTERPRETACION"
  range("AJ3") = "PESO"
  range("AK3") = "TALLA"
  range("AL3") = "IMC2 (imc2)"
  range("AM3") = "CLASIFICACION_IMC (clasificacion_imc)"
  range("AN3") = "FVC PRED DIAG_"
  range("AO3") = "FVC %TEOR DIAG_"
  range("AP3") = "FEV1 PRED DIAG_"
  range("AQ3") = "FEV1 %TEOR DIAG_"
  range("AR3") = "FEV1/FVC PRED DIAG_"
  range("AS3") = "FEV1/FVC %TEOR DIAG_"
  range("AT3") = "PEF PRED DIAG_"
  range("AU3") = "PEF %TEOR DIAG_"
  range("AV3") = "FEF 25 75 PRED DIAG_"
  range("AW3") = "FEF 25 75 %TEOR DIAG_"
  range("AX3") = "DIAG_ PPAL"
  range("AY3") = "DIAG_ OBS"
  range("AZ3") = "DIAG_ REL/1"
  range("BA3") = "DIAG_ REL/2"
  range("BB3") = "DIAG_ REL/3"
  range("BC3") = "TIPO_INTERPRETACION"
  range("BD3") = "TIPO_GRADO"
  range("BE3") = "RESULTADO_ESPIROMETRIA"
  range("BF3") = "REC/GRALES DEJAR DE FUMAR"
  range("BG3") = "REC/GRALES CONTINUAR CONTROLES EPS"
  range("BH3") = "REC/GRALES BAJAR DE PESO"
  range("BI3") = "REC/GRALES TOMAR RAYOS X TORAX"
  range("BJ3") = "REC/GRALES REALIZAR EJERC_ 3X SEMANA"
  range("BK3") = "REC/GRALES VALORAC_ EPS X NEUMOLOGIA"
  range("BL3") = "REC/LAB UTILIZAR EPR"
  range("BM3") = "REC/LAB INGRESAR SVE"
  range("BN3") = "CONTROLES MENSUAL"
  range("BO3") = "CONTROLES_BIMESTRALES"
  range("BP3") = "CONTROLES TRIMESTRAL"
  range("BQ3") = "CONTROLES SEMESTRAL"
  range("BR3") = "CONTROLES ANUAL"
  range("BS3") = "CONTROLES CONFIRMATORIA"
  range("BT3") = "TECNICA ACEPTABLE"
  range("BU3") = "calculos_diagnostico"
  range("BV3") = "RESULTADO_ESPIROMETRIA_2 (resultado_espiro)"
  range("BW3") = "espirometriatipo_interpretacion"
  range("BX3") = "espirometriatipo_grado"
  range("BY3") = "emo_id(orden_lista_trabajadoresid)"
  range("BZ3") = "ID_ESPIROMETRIA"
  range("CA3") = "SCRIPT espirometria"
  range("CB3") = "SCRIPT espiro_antecedentes_pivot"
  range("CC3") = "SCRIPT espiro_quimicos_pivot"
  range("CD3") = "SCRIPT espiro_riesgos_epp"
  range("CE3") = "SCRIPT espiro_recomendaciones_pivot"
  range("CF3") = "SCRIPT espiro_recomendaciones_lab_pivot"
  range("CG3") = "LLAVE"
  ActiveSheet.ListObjects.Add(xlSrcRange, range("$A$3:$CG$4"), , xlYes).Name = _
  "tbl_espiro_info"
  ActiveSheet.ListObjects("tbl_espiro_info").TableStyle = "TableStyleLight9"

  range("tbl_espiro_info[[#Headers],[IMC2 (imc2)]:[CLASIFICACION_IMC (clasificacion_imc)]]").Style = "Neutral"
  range("tbl_espiro_info[[#Data],[IMC2 (imc2)]:[CLASIFICACION_IMC (clasificacion_imc)]]").Style = "Notas"
  range("tbl_espiro_info[[#Headers],[RESULTADO_ESPIROMETRIA]]").Style = "Neutral"
  range("tbl_espiro_info[[#Data],[RESULTADO_ESPIROMETRIA]]").Style = "Notas"
  range("tbl_espiro_info[[#Headers],[LLAVE]]").Style = "Neutral"
  range("tbl_espiro_info[[#Data],[LLAVE]]").Style = "Notas"
  range("tbl_espiro_info[[#Headers],[calculos_diagnostico]:[emo_id(orden_lista_trabajadoresid)]]").Style = "Neutral"
  range("tbl_espiro_info[[#Data],[calculos_diagnostico]:[emo_id(orden_lista_trabajadoresid)]]").Style = "Notas"
  range("tbl_espiro_info[[#Headers],[SCRIPT espirometria]:[SCRIPT espiro_recomendaciones_lab_pivot]]").Style = "Celda de comprobaci" & ChrW(243) & "n"
  range("tbl_espiro_info[[#Data],[SCRIPT espirometria]:[SCRIPT espiro_recomendaciones_lab_pivot]]").Style = "Salida"
  
  Call formatTable("tbl_espiro_info")

End Sub

