Attribute VB_Name = "config_opto"
'namespace=vba-files\Module\configs
Option Explicit

Public Sub configOpto()
  '
  ' configOpto: realiza la configuracion inicial de las cabeceras asi como el nombre de la tabla
  '
  '
  range("A3") = "NRO IDENFICACION"
  range("B3") = "VISIO/ANT_ LABORAL ILUMINACION INADECUADA"
  range("C3") = "VISIO/ANT_ LABORAL USUARIO COMPUTADOR"
  range("D3") = "VISIO/ANT_ LABORALVISIO RADIACIONES UV"
  range("E3") = "VISIO/ANT_ LABORAL CAMBIOS TEMPREATURA"
  range("F3") = "VISIO/ANT_ LABORAL MALA VENTILACION"
  range("G3") = "VISIO/ANT_ LABORAL GASES TOXICOS"
  range("H3") = "SINTOMAS FOTOFOBIA"
  range("I3") = "SINTOMAS OJO ROJO"
  range("J3") = "SINTOMAS LAGRIMEO"
  range("K3") = "SINTOMAS VISION BORROSA"
  range("L3") = "SINTOMAS ARDOR"
  range("M3") = "SINTOMAS VISION DOBLE"
  range("N3") = "SINTOMAS CANSANCIO"
  range("O3") = "SINTOMAS MALA VISION CERCANA"
  range("P3") = "SINTOMAS DOLOR"
  range("Q3") = "SINTOMAS MALA VISON LEJANA"
  range("R3") = "SINTOMAS SECRECION"
  range("S3") = "SINTOMAS CEFALEA"
  range("T3") = "OTROS SINTOMAS"
  range("U3") = "CABEZA PARPADOS"
  range("V3") = "CABEZA PARPADOS OBS"
  range("W3") = "CABEZA CONJUNTIVAS"
  range("X3") = "CABEZA OBS CONJUNTIVAS"
  range("Y3") = "CABEZA ESCLERAS"
  range("Z3") = "CABEZA OBS ESCLERAS"
  range("AA3") = "CABEZA PUPILAS"
  range("AB3") = "CABEZA PUPILAS OBS"
  range("AC3") = "MOT/OCUL COVERT TEST LEJOS"
  range("AD3") = "MOT/OCUL COVERT TEST CERCA"
  range("AE3") = "ESTADO DE CORRECCION"
  range("AF3") = "PATOLOGIA OCULAR"
  range("AG3") = "DIAG PPAL"
  range("AH3") = "CODIGO CIE10 DIAG PPAL"
  range("AI3") = "DIAG OBS"
  range("AJ3") = "DIAG REL/1"
  range("AK3") = "DIAG REL/2"
  range("AL3") = "DIAG REL/3"
  range("AM3") = "REC CORRECCION VISUAL PARA TRABAJAR"
  range("AN3") = "REC USO AR VIDEO TRMINAL"
  range("AO3") = "REC USO DE LENTES DE PROTECCION SOLAR"
  range("AP3") = "REC USO EPP VISUAL"
  range("AQ3") = "REC PAUSAS ACTIVAS"
  range("AR3") = "REC USO RX VISION PROXIMA"
  range("AS3") = "REC USO RX DESCANSO"
  range("AT3") = "REC USO PERMANENTE RX OPTICA"
  range("AU3") = "REC PYP"
  range("AV3") = "REC LUBRICANTE OCULAR"
  range("AW3") = "RECOMENDACIONES OBS"
  range("AX3") = "REM_ VALORACION OFTALM_"
  range("AY3") = "REM_ TOPOGRAFIA CORNEAL"
  range("AZ3") = "REM_ TRATAM_ ORTOPTICA"
  range("BA3") = "REM_ TEST FARNSWORTH"
  range("BB3") = "REALIZAR PRUEBA AMBULATORIA"
  range("BC3") = "REMISIONES OBS"
  range("BD3") = "CONTROLES MENSUAL"
  range("BE3") = "CONTROLES_BIMESTRALES"
  range("BF3") = "CONTROLES TRIMESTRAL"
  range("BG3") = "CONTROLES 6 MESES"
  range("BH3") = "CONTROLES 1 A" & ChrW(209) & "O"
  range("BI3") = "CONTROLES CONFIRMATORIA"
  range("BJ3") = "estado_correccion_id"
  range("BK3") = "emo_id(orden_lista_trabajadoresid)"
  range("BL3") = "ID_OPTOMETRIA"
  range("BM3") = "OP_DIAGNOSTICO"
  range("BN3") = "SCRIPT op_optometria"
  range("BO3") = "SCRIPT op_optometria_riesgos"
  range("BP3") = "SCRIPT op_optometria_sintomas"
  range("BQ3") = "SCRIPT op_diagnostico"
  range("BR3") = "SCRIPT op_diagnostico_cie"
  range("BS3") = "SCRIPT op_optometria_recomendacion"
  range("BT3") = "SCRIPT op_optometria_remision"
  range("BU3") = "LLAVE"
  ActiveSheet.ListObjects.Add(xlSrcRange, range("$A$3:$BU$4"), , xlYes).Name = _
  "tbl_opto"
  ActiveSheet.ListObjects("tbl_opto").TableStyle = "TableStyleLight9"
  
  range("tbl_opto[[#Headers],[CODIGO CIE10 DIAG PPAL]]").Style = "Neutral"
  range("tbl_opto[[#Data],[CODIGO CIE10 DIAG PPAL]]").Style = "Notas"
  range("tbl_opto[[#Headers],[LLAVE]]").Style = "Neutral"
  range("tbl_opto[[#Data],[LLAVE]]").Style = "Notas"
  range("tbl_opto[[#Headers],[estado_correccion_id]:[emo_id(orden_lista_trabajadoresid)]]").Style = "Neutral"
  range("tbl_opto[[#Data],[estado_correccion_id]:[emo_id(orden_lista_trabajadoresid)]]").Style = "Notas"
  range("tbl_opto[[#Headers],[SCRIPT op_optometria]:[SCRIPT op_optometria_remision]]").Style = "Celda de comprobaci" & ChrW(243) & "n"
  range("tbl_opto[[#Data],[SCRIPT op_optometria]:[SCRIPT op_optometria_remision]]").Style = "Salida"
  
  Call formatTable("tbl_opto")

End Sub

